group {
    col.border_active = rgb(cba6f7)        # mauve
    col.border_inactive = rgb(45475a)      # surface1
    col.border_locked_active = rgb(f5c2e7) # pink
    col.border_locked_inactive = rgb(313244) # surface0

    groupbar {
        font_family = JetBrains Mono NF
        font_size = 15
        gradients = true
        gradient_round_only_edges = false
        gradient_rounding = 5
        height = 25
        indicator_height = 0
        gaps_in = 3
        gaps_out = 3

        text_color = rgb(cdd6f4)           # text
        col.active = rgba(cba6f7ff)        # mauve
        col.inactive = rgba(6c7086ff)      # overlay0
        col.locked_active = rgba(f5c2e7ff) # pink
        col.locked_inactive = rgba(585b70ff) # surface2
    }
}
